name: Scenario 01 - Basic Migration

on:
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/scenario-runner.yml
    with:
      scenario-id: "01"
      scenario-name: "Basic Migration"

